import { useState } from 'react';
import { Bot, X, Building2, MapPin, Settings2, Zap, CheckSquare } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog';
import { useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

import { Step1Warehouses } from './Step1Warehouses';
import { Step2Facilities } from './Step2Facilities';
import { Step3Constraints } from './Step3Constraints';
import { Step4Generate } from './Step4Generate';
import { Step5Review } from './Step5Review';

import {
  DEFAULT_COPILOT_CONSTRAINTS,
  type CopilotWarehouse,
  type CopilotFacility,
  type CopilotConstraints,
  type CopilotGenerationResult,
  type SuggestedZone,
} from '@/types/operations-copilot';

// ─── Stepper ─────────────────────────────────────────────────────────────────

const STEPS = [
  { label: 'Warehouses', icon: Building2 },
  { label: 'Facilities', icon: MapPin },
  { label: 'Constraints', icon: Settings2 },
  { label: 'Generate', icon: Zap },
  { label: 'Review', icon: CheckSquare },
] as const;

function Stepper({ current }: { current: number }) {
  return (
    <div className="flex items-center gap-1">
      {STEPS.map((step, i) => {
        const Icon = step.icon;
        const isActive = i === current - 1;
        const isDone = i < current - 1;

        return (
          <div key={step.label} className="flex items-center">
            <div
              className={`flex items-center gap-1.5 px-2.5 py-2 rounded-md text-xs font-medium transition-colors min-h-[36px] ${
                isActive
                  ? 'bg-primary text-primary-foreground'
                  : isDone
                  ? 'text-primary'
                  : 'text-muted-foreground'
              }`}
              aria-current={isActive ? 'step' : undefined}
            >
              <Icon className="h-4 w-4 shrink-0" />
              <span className="hidden md:inline">{step.label}</span>
            </div>
            {i < STEPS.length - 1 && (
              <div className={`w-5 h-[2px] mx-1 rounded-full ${isDone ? 'bg-primary' : 'bg-border'}`} />
            )}
          </div>
        );
      })}
    </div>
  );
}

// ─── Save logic ───────────────────────────────────────────────────────────────

async function persistAcceptedStructures(
  result: CopilotGenerationResult,
  workspaceId: string,
  userId: string,
): Promise<void> {
  for (const structure of result.structures) {
    const acceptedZones = structure.zones.filter(z => z.acceptance === 'accepted');
    if (acceptedZones.length === 0) continue;

    for (const zone of acceptedZones) {
      const zoneName = zone.user_name ?? zone.name;

      // 1. Create zone in `zones` table
      const { data: createdZone, error: zoneErr } = await supabase
        .from('zones' as any)
        .insert({
          name: zoneName,
          code: null,
          description: `Generated by Operations Copilot — ${new Date().toLocaleDateString()}`,
          region_center: (() => {
            if (zone.facilities.length === 0) return null;
            const lat = zone.facilities.reduce((s, f) => s + f.lat, 0) / zone.facilities.length;
            const lng = zone.facilities.reduce((s, f) => s + f.lng, 0) / zone.facilities.length;
            return { lat, lng };
          })(),
          is_active: true,
          metadata: {
            copilot_generated: true,
            warehouse_id: structure.warehouse.id,
            confidence_score: zone.confidence_score,
            confidence_level: zone.confidence_level,
            metrics: zone.metrics,
            generated_at: result.generated_at,
          },
          workspace_id: workspaceId,
          created_by: userId,
        })
        .select('id')
        .single();

      if (zoneErr) throw new Error(`Failed to create zone "${zoneName}": ${zoneErr.message}`);

      const zoneId = (createdZone as any).id as string;

      // 2. Create corresponding service area
      const sa = structure.service_areas.find(sa => sa.zone_id === zone.id);
      const { data: createdSA, error: saErr } = await supabase
        .from('service_areas')
        .insert({
          name: sa?.user_name ?? zoneName.replace('Zone', 'Service Area'),
          zone_id: zoneId,
          warehouse_id: structure.warehouse.id,
          service_type: 'general',
          is_active: true,
          priority: 'standard',
          metadata: {
            copilot_generated: true,
            policies: sa?.policies ?? [],
            route_groups: sa?.route_groups ?? [],
          },
          workspace_id: workspaceId,
          created_by: userId,
        })
        .select('id')
        .single();

      if (saErr) throw new Error(`Failed to create service area for zone "${zoneName}": ${saErr.message}`);

      const saId = (createdSA as any).id as string;

      // 3. Assign facilities to service area
      if (zone.facilities.length > 0) {
        const facilityRows = zone.facilities.map(f => ({
          service_area_id: saId,
          facility_id: f.id,
          assigned_by: userId,
        }));

        const { error: facErr } = await supabase
          .from('service_area_facilities')
          .insert(facilityRows);

        if (facErr) throw new Error(`Failed to assign facilities to service area "${zoneName}": ${facErr.message}`);

        // 4. Update facility zone_id references
        const facilityIds = zone.facilities.map(f => f.id);
        const { error: updateErr } = await supabase
          .from('facilities')
          .update({ zone_id: zoneId, updated_at: new Date().toISOString() })
          .in('id', facilityIds);

        if (updateErr) {
          // Non-fatal: log but don't fail the whole save
          console.warn(`Could not update zone_id on facilities for zone "${zoneName}":`, updateErr.message);
        }
      }
    }
  }
}

// ─── Main wizard ──────────────────────────────────────────────────────────────

interface OperationsCopilotWizardProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function OperationsCopilotWizard({ open, onOpenChange }: OperationsCopilotWizardProps) {
  const { workspaceId } = useWorkspace();
  const { user } = useAuth();
  const queryClient = useQueryClient();

  const [step, setStep] = useState<1 | 2 | 3 | 4 | 5>(1);
  const [selectedWarehouses, setSelectedWarehouses] = useState<CopilotWarehouse[]>([]);
  const [selectedFacilities, setSelectedFacilities] = useState<CopilotFacility[]>([]);
  const [constraints, setConstraints] = useState<CopilotConstraints>(DEFAULT_COPILOT_CONSTRAINTS);
  const [generationResult, setGenerationResult] = useState<CopilotGenerationResult | null>(null);
  const [isSaving, setIsSaving] = useState(false);

  function reset() {
    setStep(1);
    setSelectedWarehouses([]);
    setSelectedFacilities([]);
    setConstraints(DEFAULT_COPILOT_CONSTRAINTS);
    setGenerationResult(null);
  }

  function handleClose() {
    onOpenChange(false);
    // Don't reset — allow user to re-open and continue
  }

  async function handleSave() {
    if (!generationResult || !workspaceId) return;

    const userId = user?.id ?? '';
    setIsSaving(true);

    try {
      await persistAcceptedStructures(generationResult, workspaceId, userId);

      const acceptedCount = generationResult.structures
        .flatMap(s => s.zones)
        .filter(z => z.acceptance === 'accepted').length;

      toast.success(`${acceptedCount} zone${acceptedCount !== 1 ? 's' : ''} saved successfully`);

      // Invalidate relevant queries
      queryClient.invalidateQueries({ queryKey: ['operational-zones'] });
      queryClient.invalidateQueries({ queryKey: ['zone-metrics'] });
      queryClient.invalidateQueries({ queryKey: ['service-areas'] });
      queryClient.invalidateQueries({ queryKey: ['facilities'] });

      // Close and reset
      onOpenChange(false);
      reset();
    } catch (e: any) {
      toast.error(e?.message ?? 'Failed to save. Please try again.');
    } finally {
      setIsSaving(false);
    }
  }

  // Determine dialog size by step
  const isFullscreen = step === 5;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent
        className={`flex flex-col gap-0 p-0 overflow-hidden ${
          isFullscreen
            ? 'max-w-[95vw] w-[95vw] h-[85vh] max-h-[85vh]'
            : 'max-w-3xl max-h-[80vh]'
        }`}
        onInteractOutside={e => e.preventDefault()}
      >
        {/* Header */}
        <div className="flex items-center justify-between gap-4 px-6 py-4 border-b shrink-0">
          <div className="flex items-center gap-3 min-w-0">
            <div className="p-2.5 rounded-lg bg-primary/10 shrink-0">
              <Bot className="h-5 w-5 text-primary" />
            </div>
            <div className="min-w-0">
              <DialogTitle className="text-base font-semibold leading-tight truncate">
                Operations Copilot
              </DialogTitle>
              <p className="text-xs text-muted-foreground mt-0.5 truncate">
                AI-assisted zone inference &amp; operational structure setup
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3 shrink-0">
            <Stepper current={step} />
            <button
              onClick={handleClose}
              aria-label="Close dialog"
              className="inline-flex items-center justify-center h-9 w-9 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className={`flex-1 min-h-0 ${step === 5 ? 'overflow-hidden' : 'overflow-auto'}`}>
          <div className={`${step === 5 ? 'h-full flex flex-col p-4' : 'p-6'}`}>
            {step === 1 && (
              <Step1Warehouses
                selected={selectedWarehouses}
                onSelectionChange={setSelectedWarehouses}
                onNext={() => setStep(2)}
              />
            )}
            {step === 2 && (
              <Step2Facilities
                selected={selectedFacilities}
                onSelectionChange={setSelectedFacilities}
                onNext={() => setStep(3)}
                onBack={() => setStep(1)}
              />
            )}
            {step === 3 && (
              <Step3Constraints
                constraints={constraints}
                onConstraintsChange={setConstraints}
                onNext={() => setStep(4)}
                onBack={() => setStep(2)}
                warehouseCount={selectedWarehouses.length}
                facilityCount={selectedFacilities.length}
                warehouses={selectedWarehouses}
                facilities={selectedFacilities}
              />
            )}
            {step === 4 && (
              <Step4Generate
                warehouses={selectedWarehouses}
                facilities={selectedFacilities}
                constraints={constraints}
                onComplete={result => {
                  setGenerationResult(result);
                  setStep(5);
                }}
                onBack={() => setStep(3)}
                existingResult={generationResult}
              />
            )}
            {step === 5 && generationResult && (
              <Step5Review
                result={generationResult}
                onResultChange={setGenerationResult}
                onSave={handleSave}
                onBack={() => setStep(4)}
                isSaving={isSaving}
              />
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
