/**
 * =====================================================
 * Scheduling Copilot Types
 * =====================================================
 * Types for the constraint-aware operational orchestration
 * mode (Scheduling Copilot).
 *
 * Philosophy: user defines WHAT needs to happen,
 * system determines HOW it can feasibly happen.
 */

// =====================================================
// PLANNING CANDIDATE
// =====================================================
// A facility PLUS its full operational dispatch context.
// Sources resolve into PlanningCandidate[] instead of Facility[].

export type CopilotPriority = 'routine' | 'urgent' | 'critical';
export type PackagingStatus = 'complete' | 'partial' | 'pending';

export interface PlanningCandidate {
  facility_id: string;
  facility_name: string;
  facility_code?: string;
  lga?: string;
  zone?: string;
  lat?: number;
  lng?: number;

  requisition_ids: string[];
  invoice_ids: string[];

  dispatch_ready: boolean;
  slot_demand: number;
  total_weight: number;   // kg
  total_volume: number;   // m3

  cold_chain: boolean;
  priority: CopilotPriority;
  packaging_status: PackagingStatus;
}

// =====================================================
// PLANNING INTENT
// =====================================================
// User-defined operational preferences for this planning session.

export interface PlanningIntent {
  planning_window_start: string;   // ISO date YYYY-MM-DD
  planning_window_end: string;     // ISO date YYYY-MM-DD
  priority: CopilotPriority;

  // Operational preferences
  minimize_vehicles: boolean;
  respect_facility_hours: boolean;
  prioritize_cold_chain: boolean;
  balance_fleet_utilization: boolean;

  // Optional constraints
  max_run_duration_hours: number;  // default 8
  shift_start_hour: number;        // default 8 (8AM)
  shift_end_hour: number;          // default 18 (6PM)
}

export const DEFAULT_PLANNING_INTENT: PlanningIntent = {
  planning_window_start: '',
  planning_window_end: '',
  priority: 'routine',
  minimize_vehicles: true,
  respect_facility_hours: true,
  prioritize_cold_chain: true,
  balance_fleet_utilization: false,
  max_run_duration_hours: 8,
  shift_start_hour: 8,
  shift_end_hour: 18,
};

// =====================================================
// LOGICAL BATCH
// =====================================================
// Route-aware grouping of candidates. NOT an execution trip.

export interface LogicalBatch {
  id: string;
  label: string;                    // e.g. "Batch A"
  candidates: PlanningCandidate[];
  grouping_reason: string;          // e.g. "Geographic proximity (Kano North)"
  total_slot_demand: number;
  total_weight: number;
  total_volume: number;
  has_cold_chain: boolean;
  segments?: BatchSegment[];        // set if capacity-split was needed
}

export interface BatchSegment {
  id: string;
  label: string;                    // e.g. "Segment 1"
  candidates: PlanningCandidate[];
  total_slot_demand: number;
}

// =====================================================
// FEASIBILITY WARNING
// =====================================================

export type FeasibilityWarningType =
  | 'shift_exceeded'
  | 'vehicle_unavailable'
  | 'facility_closed'
  | 'cold_chain_mismatch'
  | 'capacity_exceeded'
  | 'additional_vehicle_required'
  | 'resource_saturation'
  | 'driver_overlap';

export interface FeasibilityWarning {
  type: FeasibilityWarningType;
  message: string;
  severity: 'warning' | 'error';
}

// =====================================================
// DISPATCH RUN PROPOSAL
// =====================================================
// A proposed execution run generated by the copilot.
// User can review, adjust, override, then approve.

export interface DispatchRunProposal {
  id: string;
  run_number: number;
  planned_date: string;             // ISO date YYYY-MM-DD
  planned_departure: string;        // HH:mm  e.g. "08:00"
  planned_return: string;           // HH:mm  e.g. "13:00"
  estimated_duration_hours: number;

  vehicle_id: string | null;
  vehicle_model?: string;
  vehicle_plate?: string;
  vehicle_capacity_slots?: number;

  driver_id: string | null;
  driver_name?: string;

  candidates: PlanningCandidate[];
  total_slot_demand: number;
  total_weight: number;
  utilization_pct: number;          // 0–100

  feasibility_warnings: FeasibilityWarning[];
  has_cold_chain: boolean;

  // User overrides
  user_overridden: boolean;
}

// =====================================================
// RESOURCE OCCUPANCY ENTRY
// =====================================================

export type ResourceStatus = 'available' | 'occupied' | 'maintenance';

export interface ResourceOccupancyEntry {
  resource_id: string;
  resource_type: 'vehicle' | 'driver';
  resource_name: string;
  status: ResourceStatus;
  occupied_until?: string;          // ISO datetime
  note?: string;
}

// =====================================================
// COPILOT EXECUTION PLAN
// =====================================================
// The full output of the orchestration engine.

export interface CopilotPlan {
  plan_id: string;
  generated_at: string;             // ISO datetime
  planning_window_start: string;
  planning_window_end: string;

  logical_batches: LogicalBatch[];
  dispatch_runs: DispatchRunProposal[];
  unassigned_candidates: PlanningCandidate[];
  resource_occupancy: ResourceOccupancyEntry[];

  summary: {
    total_candidates: number;
    total_assigned: number;
    total_unassigned: number;
    total_runs: number;
    total_days: number;
    total_vehicles_used: number;
    total_warnings: number;
    estimated_execution_days: number;
  };
}
