/**
 * SlotGrid — Visual slot layout for a vehicle's cargo tiers.
 *
 * Renders tiers top-to-bottom (Upper → Lower).
 * Each slot accepts drag-drop. States: empty / occupied / drag-over / invalid.
 */

import { cn } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { X } from 'lucide-react';
import type { VehicleSlot } from '@/fleetops/payload/types';
import type { AssignableFacility } from '@/fleetops/payload/types';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface SlotGridProps {
  /** All slots for the vehicle, generated by generateVehicleSlotMap */
  slots: VehicleSlot[];
  /** Current assignments: slot_key → facility */
  assignments: Map<string, AssignableFacility>;
  /** Facility currently being dragged (null if none) */
  draggingFacility: AssignableFacility | null;
  /** Called when a facility is dropped onto an empty slot */
  onSlotDrop: (slotKey: string) => void;
  /** Called when the user removes a facility from a slot */
  onSlotClear: (slotKey: string) => void;
  /** Compact mode — smaller cells, used in read-only views */
  compact?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function groupByTier(slots: VehicleSlot[]): { tierName: string; tierOrder: number; slots: VehicleSlot[] }[] {
  const map = new Map<string, { tierName: string; tierOrder: number; slots: VehicleSlot[] }>();

  for (const slot of slots) {
    const key = slot.tier_name;
    if (!map.has(key)) {
      map.set(key, { tierName: slot.tier_name, tierOrder: slot.tier_order, slots: [] });
    }
    map.get(key)!.slots.push(slot);
  }

  // Sort tiers: highest tier_order first (Upper on top physically)
  return [...map.values()].sort((a, b) => b.tierOrder - a.tierOrder);
}

const TIER_ORDER_LABELS: Record<number, string> = {
  1: 'Lower',
  2: 'Middle',
  3: 'Upper',
  4: 'Top',
};

function tierLabel(tierOrder: number): string {
  return TIER_ORDER_LABELS[tierOrder] ?? `Tier ${tierOrder}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// SlotCell
// ─────────────────────────────────────────────────────────────────────────────

interface SlotCellProps {
  slot: VehicleSlot;
  facility: AssignableFacility | undefined;
  isDraggingOver: boolean;
  canDrop: boolean;
  onDragOver: (e: React.DragEvent) => void;
  onDragLeave: () => void;
  onDrop: (e: React.DragEvent) => void;
  onClear: () => void;
  compact: boolean;
}

function SlotCell({
  slot,
  facility,
  isDraggingOver,
  canDrop,
  onDragOver,
  onDragLeave,
  onDrop,
  onClear,
  compact,
}: SlotCellProps) {
  const occupied = !!facility;

  const cellCls = cn(
    'relative border-2 rounded flex items-center justify-center transition-all select-none',
    compact ? 'h-10 w-10' : 'h-14 w-14',
    // Base state
    !occupied && !isDraggingOver && 'border-dashed border-border/50 bg-muted/20 hover:border-border',
    // Occupied
    occupied && 'border-solid border-primary/40 bg-primary/5',
    // Drag over — valid
    isDraggingOver && canDrop && 'border-solid border-blue-500 bg-blue-50 dark:bg-blue-950 scale-105',
    // Drag over — invalid (occupied)
    isDraggingOver && !canDrop && 'border-solid border-destructive/60 bg-destructive/10',
  );

  return (
    <div
      className={cellCls}
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
      title={
        occupied
          ? `${facility!.name ?? facility!.id}${facility!.estimated_weight ? ` · ${facility!.estimated_weight} kg` : ''}`
          : `Slot ${slot.slot_number} — empty (${slot.capacity_kg} kg)`
      }
    >
      {occupied ? (
        <>
          {/* Facility label */}
          <span className="text-[10px] font-medium text-center leading-tight px-0.5 line-clamp-2 text-primary">
            {compact
              ? String(slot.slot_number)
              : (facility!.name ?? facility!.id).slice(0, 6)}
          </span>

          {/* Clear button */}
          {!compact && (
            <button
              onClick={(e) => { e.stopPropagation(); onClear(); }}
              className="absolute -top-1.5 -right-1.5 h-4 w-4 rounded-full bg-destructive text-destructive-foreground flex items-center justify-center opacity-0 group-hover:opacity-100 hover:opacity-100 transition-opacity"
              aria-label="Remove assignment"
            >
              <X className="h-2.5 w-2.5" />
            </button>
          )}
        </>
      ) : (
        <span className={cn('text-muted-foreground/40 font-mono', compact ? 'text-[9px]' : 'text-[10px]')}>
          {slot.slot_number}
        </span>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// SlotGrid
// ─────────────────────────────────────────────────────────────────────────────

export function SlotGrid({
  slots,
  assignments,
  draggingFacility,
  onSlotDrop,
  onSlotClear,
  compact = false,
}: SlotGridProps) {
  const tiers = groupByTier(slots);

  // Track which slot is being dragged over
  const [dragOverSlot, setDragOverSlot] = React.useState<string | null>(null);

  if (slots.length === 0) {
    return (
      <div className="flex items-center justify-center h-32 text-sm text-muted-foreground border-2 border-dashed rounded-lg">
        No slots configured for this vehicle
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {tiers.map(({ tierName, tierOrder, slots: tierSlots }) => {
        const occupiedCount = tierSlots.filter((s) => assignments.has(s.slot_key)).length;
        const totalCount = tierSlots.length;

        return (
          <div key={tierName}>
            {/* Tier header */}
            <div className="flex items-center gap-2 mb-2">
              <Badge variant="outline" className="text-xs font-medium">
                {tierLabel(tierOrder)}
              </Badge>
              <span className="text-xs text-muted-foreground">
                {occupiedCount}/{totalCount} slots
              </span>
              {occupiedCount === totalCount && totalCount > 0 && (
                <Badge variant="secondary" className="text-xs">Full</Badge>
              )}
            </div>

            {/* Slot row */}
            <div className="flex flex-wrap gap-1.5 group">
              {tierSlots.map((slot) => {
                const facility = assignments.get(slot.slot_key);
                const isOver = dragOverSlot === slot.slot_key;
                const canDrop = !facility; // can only drop on empty slots

                return (
                  <SlotCell
                    key={slot.slot_key}
                    slot={slot}
                    facility={facility}
                    isDraggingOver={isOver && !!draggingFacility}
                    canDrop={canDrop}
                    compact={compact}
                    onDragOver={(e) => {
                      e.preventDefault();
                      e.dataTransfer.dropEffect = canDrop ? 'move' : 'none';
                      setDragOverSlot(slot.slot_key);
                    }}
                    onDragLeave={() => setDragOverSlot(null)}
                    onDrop={(e) => {
                      e.preventDefault();
                      setDragOverSlot(null);
                      if (canDrop) onSlotDrop(slot.slot_key);
                    }}
                    onClear={() => onSlotClear(slot.slot_key)}
                  />
                );
              })}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// React import (needs to be explicit for useState in non-JSX file sections)
import React from 'react';
